name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  label:
    types: [created, edited, deleted]
  push:
    branches:
      - main
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'feature/**'
      - 'releases/**'
      
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
